"""
ChangeImpactAnalyzer: Evaluates how Git diffs, working-tree edits, and commits
impact component structural metrics, dependency topology, and ML-predicted risk.
"""
import ast
import logging
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple
import pandas as pd

from analysis.dependency_analyzer import DependencyGraph
from ingestion.git_loader import CommitDetail, FileDiffItem
from ml.predict import ComponentRiskProfile, RiskPredictor
from ml.train import TrainedModelBundle

logger = logging.getLogger(__name__)


@dataclass
class SignalDelta:
    """Represents the quantitative change in a specific model signal."""
    signal_name: str
    display_name: str
    before_value: float
    after_value: float
    unit: str = ""
    estimated_contribution: float = 0.0  # percentage points estimated impact


@dataclass
class ComponentChangeImpact:
    """Detailed change impact evaluation for a single component."""
    component_name: str
    filepath: str
    change_type: str  # ADDED, MODIFIED, DELETED
    insertions: int
    deletions: int
    current_risk_pct: int
    current_risk_category: str
    current_risk_prob: float
    proposed_risk_pct: int
    proposed_risk_category: str
    proposed_risk_prob: float
    risk_delta_pct: int  # proposed - current
    changed_signals: List[SignalDelta]
    dependency_changes: int  # +1, -1, 0
    structural_changes: int
    is_estimated: bool = True
    explanation: str = ""


@dataclass
class RepositoryChangeImpactSummary:
    """Summary of changes and model impact across all affected files in a commit or preview."""
    total_files_affected: int
    total_components_affected: int
    total_dependency_changes: int
    total_structural_changes: int
    component_impacts: List[ComponentChangeImpact]
    aggregate_before_risk_avg: float
    aggregate_after_risk_avg: float
    aggregate_delta_pct: int
    scientific_disclaimer: str = (
        "Change impact estimates are generated by recalculating structural and churn signals "
        "and evaluating the modified component representation through the trained model."
    )


class ChangeImpactAnalyzer:
    """Analyzes code modifications and predicts the resulting shift in ML risk."""

    def __init__(
        self,
        model_bundle: TrainedModelBundle,
        base_graph: DependencyGraph,
        component_profiles: List[ComponentRiskProfile]
    ):
        self.bundle = model_bundle
        self.base_graph = base_graph
        self.profiles_by_path: Dict[str, ComponentRiskProfile] = {
            p.filepath.replace("\\", "/").lower(): p for p in component_profiles
        }
        self.predictor = RiskPredictor()

    def analyze_file_diff(
        self,
        filepath: str,
        diff_text: str,
        change_type: str = "MODIFIED",
        insertions: int = 0,
        deletions: int = 0
    ) -> Optional[ComponentChangeImpact]:
        """Evaluates how modifying a single file alters its structural metrics and risk."""
        norm_path = filepath.replace("\\", "/").lower()
        
        # Match with known profile
        profile = None
        for ppath, p in self.profiles_by_path.items():
            if norm_path.endswith(ppath) or ppath.endswith(norm_path) or norm_path == ppath:
                profile = p
                break

        if not profile:
            # If component was not part of static analysis, return basic unestimated record
            return None

        # 1. Parse Diff for Structural Shifts
        added_lines = [line[1:] for line in diff_text.split("\n") if line.startswith("+") and not line.startswith("+++")]
        removed_lines = [line[1:] for line in diff_text.split("\n") if line.startswith("-") and not line.startswith("---")]

        actual_ins = insertions if insertions > 0 else len(added_lines)
        actual_dels = deletions if deletions > 0 else len(removed_lines)

        # Estimate complexity shift: count branching keywords in added/removed lines
        branch_keywords = ["if ", "elif ", "else:", "for ", "while ", "try:", "except ", "except:", "with ", "def ", "class "]
        complexity_inc = sum(sum(1 for kw in branch_keywords if kw in line) for line in added_lines)
        complexity_dec = sum(sum(1 for kw in branch_keywords if kw in line) for line in removed_lines)
        comp_delta = complexity_inc - complexity_dec

        # Estimate dependency shift: count import statements added/removed
        import_kw = ["import ", "from "]
        dep_inc = sum(1 for line in added_lines if any(line.strip().startswith(kw) for kw in import_kw))
        dep_dec = sum(1 for line in removed_lines if any(line.strip().startswith(kw) for kw in import_kw))
        dep_delta = dep_inc - dep_dec

        # Clone and mutate dependency graph if applicable
        sim_graph = self.base_graph.clone()
        src_node = profile.filepath
        if dep_delta > 0:
            sim_graph.add_dependency(src_node, "simulated.external.module")
        elif dep_delta < 0 and sim_graph.get_out_degree(src_node) > 0:
            succs = sim_graph.get_successors(src_node)
            if succs:
                sim_graph.remove_dependency(src_node, succs[0])

        new_struct = sim_graph.get_metrics_for_all().get(src_node)
        new_deps = new_struct.dependency_count if new_struct else max(0, profile.dependency_count + dep_delta)
        new_cent = new_struct.centrality if new_struct else profile.centrality
        new_deg = new_struct.degree if new_struct else profile.degree

        # 2. Mutate Features
        mod_features = profile.to_dict()
        old_comp = profile.complexity
        new_comp = max(1, old_comp + comp_delta)
        mod_features["complexity"] = new_comp

        old_churn = profile.churn
        new_churn = old_churn + (actual_ins + actual_dels)
        mod_features["churn"] = new_churn

        old_rchurn = profile.recent_churn
        new_rchurn = old_rchurn + (actual_ins + actual_dels)
        mod_features["recent_churn"] = new_rchurn

        old_loc = profile.loc
        new_loc = max(1, old_loc + (actual_ins - actual_dels))
        mod_features["loc"] = new_loc

        mod_features["dependency_count"] = new_deps
        mod_features["centrality"] = new_cent
        mod_features["degree"] = new_deg

        # 3. Predict on Modified Vector
        df_mod = pd.DataFrame([mod_features])
        pred_res = self.predictor.predict(self.bundle, df_mod)
        sim_profile = pred_res.profiles[0]

        # 4. Compute Signals & Deltas
        signal_deltas: List[SignalDelta] = []
        if new_comp != old_comp:
            signal_deltas.append(SignalDelta(
                signal_name="complexity",
                display_name="Complexity",
                before_value=old_comp,
                after_value=new_comp,
                estimated_contribution=round((new_comp - old_comp) * 2.5, 1)
            ))
        if new_deps != profile.dependency_count:
            signal_deltas.append(SignalDelta(
                signal_name="dependency_count",
                display_name="Dependencies",
                before_value=profile.dependency_count,
                after_value=new_deps,
                estimated_contribution=round((new_deps - profile.dependency_count) * 4.0, 1)
            ))
        if new_churn != old_churn:
            signal_deltas.append(SignalDelta(
                signal_name="churn",
                display_name="Churn",
                before_value=old_churn,
                after_value=new_churn,
                unit="lines",
                estimated_contribution=round((new_churn - old_churn) * 0.05, 1)
            ))
        if new_loc != old_loc:
            signal_deltas.append(SignalDelta(
                signal_name="loc",
                display_name="Lines of Code",
                before_value=old_loc,
                after_value=new_loc,
                unit="lines"
            ))

        delta_pct = sim_profile.risk_percentage - profile.risk_percentage

        explanation = (
            f"Risk shifted by {delta_pct:+d} percentage points ({profile.risk_percentage}% → {sim_profile.risk_percentage}%) "
            f"due to changes in complexity ({old_comp} → {new_comp}), churn (+{actual_ins + actual_dels} lines), "
            f"and dependency footprint ({profile.dependency_count} → {new_deps})."
        )

        return ComponentChangeImpact(
            component_name=profile.component_name,
            filepath=profile.filepath,
            change_type=change_type,
            insertions=actual_ins,
            deletions=actual_dels,
            current_risk_pct=profile.risk_percentage,
            current_risk_category=profile.risk_category,
            current_risk_prob=profile.risk_probability,
            proposed_risk_pct=sim_profile.risk_percentage,
            proposed_risk_category=sim_profile.risk_category,
            proposed_risk_prob=sim_profile.risk_probability,
            risk_delta_pct=delta_pct,
            changed_signals=signal_deltas,
            dependency_changes=dep_delta,
            structural_changes=abs(comp_delta) + abs(dep_delta),
            is_estimated=True,
            explanation=explanation
        )

    def analyze_commit_or_preview(
        self,
        diff_items: List[FileDiffItem]
    ) -> RepositoryChangeImpactSummary:
        """Evaluates multiple file diffs from a commit or working-tree change preview."""
        impacts: List[ComponentChangeImpact] = []
        tot_dep_changes = 0
        tot_struct_changes = 0

        for item in diff_items:
            res = self.analyze_file_diff(
                filepath=item.filepath,
                diff_text=item.patch,
                change_type=item.change_type,
                insertions=item.insertions,
                deletions=item.deletions
            )
            if res:
                impacts.append(res)
                tot_dep_changes += abs(res.dependency_changes)
                tot_struct_changes += res.structural_changes

        if impacts:
            avg_before = sum(i.current_risk_pct for i in impacts) / len(impacts)
            avg_after = sum(i.proposed_risk_pct for i in impacts) / len(impacts)
            delta = int(round(avg_after - avg_before))
        else:
            avg_before = 0.0
            avg_after = 0.0
            delta = 0

        return RepositoryChangeImpactSummary(
            total_files_affected=len(diff_items),
            total_components_affected=len(impacts),
            total_dependency_changes=tot_dep_changes,
            total_structural_changes=tot_struct_changes,
            component_impacts=impacts,
            aggregate_before_risk_avg=avg_before,
            aggregate_after_risk_avg=avg_after,
            aggregate_delta_pct=delta
        )
